### PR TITLE
GHC-202: Add release notes

### PR DESCRIPTION
**Pull request by Ruhanga**
Ticket: https://mekomsolutions.atlassian.net/browse/GHC-202

cc @kdaud, @suruchee

### CODE REVIEW

**Comment by nuhuhmutebi** [comment]
Hi @Ruhanga find the review comments below:

[This](https://github.com/globalhealthcoalition/bahmni-distro-ghc/pull/10/commits/67b77802f01380ad9e5a59878beb5b0941a2abaf#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R34) is in fact not applied here. It's to be applied in the Bahmni Appointments.

Let's separate [this ](https://github.com/globalhealthcoalition/bahmni-distro-ghc/pull/10/commits/67b77802f01380ad9e5a59878beb5b0941a2abaf#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R35) into two.

The following are missing add them please
1. https://mekomsolutions.atlassian.net/browse/GHC-171
2. https://mekomsolutions.atlassian.net/browse/GHC-160

**Comment by Ruhanga** [comment]
Thanks for the review @nuhuhmutebi 

>[This](https://github.com/globalhealthcoalition/bahmni-distro-ghc/pull/10/commits/67b77802f01380ad9e5a59878beb5b0941a2abaf#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R34) is in fact not applied here. It's to be applied in the Bahmni Appointments.

Since the effects are visible for this release, that's why I include what this release brings. Maybe you could suggest a proper phrasing for that point?

**Comment by Ruhanga** [comment]
As for [GHC-171](https://mekomsolutions.atlassian.net/browse/GHC-171), it was addressed through another ticket [GHC-175](https://mekomsolutions.atlassian.net/browse/GHC-175), while [GHC-160](https://mekomsolutions.atlassian.net/browse/GHC-160) was resolved as `won't do`.

**Comment by nuhuhmutebi** [comment]
This is fine

**Comment by nuhuhmutebi** [comment]
This is fine

**Review by nuhuhmutebi — APPROVED** [review]
This is ready to be merged. Thanks @Ruhanga

**Pull request merged**
